services:
  - type: web
    name: BookMyStay
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        scope: build
      - key: NODE_ENV
        value: production
